force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <label>Contract</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <label>Doctor</label>
    <referenceTo>Doctor__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Hospital__c.field-meta.xml
<CustomField>
    <fullName>Hospital__c</fullName>
    <label>Hospital</label>
    <referenceTo>Hospital__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Doctor__c/Doctor__c.object-meta.xml
<CustomObject>
    <label>Doctor</label>
    <nameField>
        <label>Doctor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hospital__c/Hospital__c.object-meta.xml
<CustomObject>
    <label>Hospital</label>
    <nameField>
        <label>Hospital Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hospitals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/HDP_ContractsCheck.cls
/**
 * Created by alisa.borkowska on 01.12.2022.
 */

public with sharing class HDP_ContractsCheck {

    public static void contractsDateChecking(List<sObject> newListObj, Map<Id, sObject> newMapObj) {
        Set<Id> hospitalIds = new Set<Id>();
        Set<Id> doctorsIds = new Set<Id>();

        for (sObject contract : newListObj) {
            Contract__c ctr = (Contract__c) contract;
            hospitalIds.add (ctr.Hospital__c);
            doctorsIds.add (ctr.Doctor__c);
        }

        List<Hospital__c> hospitals = [SELECT Id FROM Hospital__c WHERE Id IN :hospitalIds];
        List<Doctor__c> doctors = [SELECT Id FROM Doctor__c WHERE Id IN :doctorsIds];

        List<Contract__c> contracts = [
                SELECT Id, Start_Date__c, End_Date__c, Name
                FROM Contract__c
                WHERE Hospital__c IN :hospitals
                AND Doctor__c IN :doctors
                AND Id NOT IN :newListObj
        ];

        for (sObject newContract : newListObj) {
            Contract__c newCtr = (Contract__c) newContract;
            for (Contract__c existingContract : contracts) {
                if (newCtr.End_Date__c < existingContract.Start_Date__c ||
                        newCtr.Start_Date__c > existingContract.End_Date__c) {
                    continue;
                } else {
                    String errorInfo = System.Label.Overlapping + ' ' + existingContract.Name;
                    newContract.addError(errorInfo);
                }

            }
        }
    }

}